### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by mickeypash** [sirupsen/napkin-math#10]
Hey Simon,

Thanks for the great talk and resource!
I'm quite new to all things `perf` and also haven't really used Rust before.
I had a couple of questions:
1. When I ran your tool on an AWS ec2 host running Ubuntu 18.4 and all the memory functions failed. I wonder if that's related to some host restrictions?
2. I didn't see [Brendan Gregg](http://www.brendangregg.com/perf.html#TimedProfiling) in any of your references, I think his work might be worth mentioning here. 

Cheers

**Comment by sirupsen** [comment]
Hey Mickey, do you have a trace?

**Comment by mickeypash** [comment]
🙈  Apologies it, turns out it's due to the instance size. It was OOMing.

**Comment by sirupsen** [comment]
All good friend! Can you let me know the numbers from the bigger instance? I'd like to collect those too

**Comment by mickeypash** [comment]
Will, do! Currently cost-saving and using free-tier 🙈 .
