### ISSUE TITLE
X/Y/Z (T) Plots

### ISSUE THREAD

**Issue by chadbrewbaker** [sirupsen/napkin-math#19]
https://www.twitch.tv/videos/1450298775 by @colmmacc.

What is the chance of  X at timescale T experiencing a fault rate Y for Z time? 

https://github.com/SiegeLord/RustGnuplot looks sane for a plotting API.  Store community sourced timings in zstd compressed sqlite database as an external binary?

**Comment by sirupsen** [comment]
@chadbrewbaker hey, you'll need to provide a bit more detail here to explain what you're thinking about. Can't expect me to watch that full video to respond to your ticket :)
