### ISSUE TITLE
Discrepancy in SSD read with Latency numbers every programmer should know

### ISSUE THREAD

**Issue by avmohan** [sirupsen/napkin-math#21]
Hi,
In this site, it's mentioned 1,000,000 bytes from SSD takes 31μs (2020)
https://colin-scott.github.io/personal_website/research/interactive_latency.html

But as per the numbers published in this repo, it's 200μs for 1M sequential read from SSD. 

Could you please help me understand how this discrepancy?
Or are they referring to different hardware?

**Comment by thundergolfer** [comment]
That website _projects forward_ from 2012 data. It is not at all accurate. See https://news.ycombinator.com/item?id=30549139 for more context and a lot more people being confused about this 🙂.

**Comment by sirupsen** [comment]
@avmohan these numbers are from real cloud instances running code you can review in the repo. As @thundergolfer said, I don't think they've grown as linearly as that site implies!
