### ISSUE TITLE
Suggestion: rename Random SSD Seek to Random SSD Read

### ISSUE THREAD

**Issue by veeral-patel** [sirupsen/napkin-math#25]
My understanding is that a sequential SSD read takes 1us and a random SSD read takes 100us.

In the repository, "Random SSD Seek" should be renamed to "Random SSD Read" so you can compare it to "Sequential SSD Read" easily.

Otherwise, users may think that to do a random SSD read, you first need to do a random SSD seek and then a sequential SSD read.

**Comment by sirupsen** [comment]
@veeral-patel I'd say you're right about this, the main reason I used "seek" is because it's HDD vocabulary... But I think we can bias towards SSDs/network disk based vocabulary now, and regardless, you're right a seek doesn't do a read. I'll update this soon

**Comment by sirupsen** [comment]
Done, thanks for the suggestion!
