### ISSUE TITLE
Any tools to get real metrics reliably

### ISSUE THREAD

**Issue by amosbird** [sirupsen/napkin-math#7]
I wonder if there exists a tool that can inspect the hardware in detail and outputs a report with those metrics so that we can do `napkin-math` more accurately. And it also helps comparing different machines when doing performance experiments

**Comment by sirupsen** [comment]
That’s exactly what the rust program in the repo is for! Most calculations will be within an order of magnitude on different severs, but I have wanted to provide bookends, yes.
